"""conversation memory tables + ingestion_jobs backup/restore columns

Combines two unrelated changes generated together in one autogenerate
pass (Phase 6 development): the new `conversations`/`conversation_messages`
tables (Phase 6, item 7 — conversation memory), and a fix for a
pre-existing schema drift bug found while working on this migration —
`IngestionJob.backup_key`/`restore_to_key` existed on the SQLAlchemy
model (used by the Phase 5 upload-replacement backup/restore flow — see
app/services/ingestion_jobs.py) but were NEVER migrated, meaning
`alembic upgrade head` against a fresh production database would have
created an `ingestion_jobs` table missing two columns the application
code depends on. Caught via `alembic revision --autogenerate` correctly
detecting the drift; SQLite dev/test databases (created via
`Base.metadata.create_all()`, not via migrations) never surfaced this.

Revision ID: b811bd877381
Revises: f3a1c9d2e7b4
Create Date: 2026-08-20 01:28:10.719872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b811bd877381'
down_revision: Union[str, Sequence[str], None] = 'f3a1c9d2e7b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('anonymous_session_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('document_ids', sa.Text(), nullable=False),
    sa.Column('rolling_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(owner_id IS NULL) != (anonymous_session_id IS NULL)', name='ck_conversations_exactly_one_owner'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_anonymous_session_id'), 'conversations', ['anonymous_session_id'], unique=False)
    op.create_index(op.f('ix_conversations_owner_id'), 'conversations', ['owner_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', sa.Text(), nullable=False),
    sa.Column('retrieved_chunk_ids', sa.Text(), nullable=False),
    sa.Column('query_type', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_created_at'), 'conversation_messages', ['created_at'], unique=False)
    op.add_column('ingestion_jobs', sa.Column('backup_key', sa.String(length=1024), nullable=True))
    op.add_column('ingestion_jobs', sa.Column('restore_to_key', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_jobs', 'restore_to_key')
    op.drop_column('ingestion_jobs', 'backup_key')
    op.drop_index(op.f('ix_conversation_messages_created_at'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_conversations_owner_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_anonymous_session_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###